namespace PathwayNavigator {

    /**
     * Expected format of the node (there are no required fields)
    */
    export interface jsTree {
        /**
         * the unique id of a tree node, will be autogenerated if omitted
        */
        id: string
        /**
         * node text
        */
        text: string
        /**
         * string for custom
        */
        icon?: string
        state?: {
            /**
             * is the node open
            */
            opened: boolean,
            /**
             * is the node disabled
            */
            disabled: boolean,
            /**
             * is the node selected
            */
            selected: boolean
        },
        /**
         * array of strings or objects
        */
        children?: jsTree[]
        /**
         * attributes for the generated LI node
        */
        li_attr?: {}
        /**
         * attributes for the generated A node
        */
        a_attr?: {}
    }
}
